services:
  - type: web
    name: orgmedi-backend
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: orgmedi-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: orgmedi-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: orgmedi-db
          property: password
    disk:
      name: orgmedi-data
      mountPath: /data
      sizeGB: 1

  - type: web
    name: orgmedi-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    staticPublishPath: dist/Proyecto/browser
    envVars:
      - key: NODE_ENV
        value: production

  - type: postgresql
    name: orgmedi-db
    ipWhitelist: []
